---
- hosts: all #vm_ip
  become: yes
  tasks:
    - name: test for python3 availablity on host for ansible
      raw: test -e /usr/bin/python3 || (apt install python3 -y)
      
    - name: update apt
      apt:
        update_cache: yes

    - name: install Java jdk-17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: download Jenkins war file
      get_url:
        url: https://get.jenkins.io/war-stable/latest/jenkins.war
        dest: /tmp/jenkins.war

    - name: create Jenkins group
      group:
        name: jenkins
        state: present

    - name: create user
      user:
        name: jenkins # or devops
        groups: jenkins
        createhome: yes
        system: yes

    - name: create Jenkins data directory
      file:
        path: /var/lib/jenkins
        state: directory
        owner: jenkins
        group: jenkins

    - name: run Jenkins war file
      shell: |
        nohup java -jar /tmp/jenkins.war > /var/log/jenkins.log 2>&1 &
        # java -jar /tmp/jenkins.war --httpPort=8085 --httpListenAddress=0.0.0.0 --daemon 

    - name: start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: install groovy
      apt:
        name: groovy
        state: present

    - name: run the jenkinsfile
      shell: |
        java -jar /usr/share/jenkins/cli/cli.jar -s http://localhost:8085/ execute -f ./Jenkinsfile

    - name: install python3
      apt:
        name:
          - python3
          - python3-pip
        state: present    
